[localhost]
127.0.0.1 ansible_connection=local

[aws_ec2_instances]
# Target servers will be dynamically appended downstream by our pipelines!

[k8s_orchestrators]
# Local cluster nodes or external cloud clusters live here!

